### ISSUE TITLE
GopherCon Trip Report

### ISSUE THREAD

**Issue by jbowen93** [30x/project-management#112]
Summary of high points of the conference and valuable insights that should be shared with the company.

**Comment by jbowen93** [comment]
High Points
- Nil Talk
- Dave Cheney on Errors
- Discussion with Kelsey Hightower
- Rob Pike on the assembler (not super relevant to us)
- Twitch talk on Go library design

I'm sure some stuff is slipping my mind atm.

**Comment by whitlockjc** [comment]
I learned a few things about Go that I didn't know before.  This is more due to us not having a need for it yet but still good to know for the future.  It was awesome hanging out with Kelsey Hightower and talking about Kubernetes.  Not only did I learn some new `kubectl` commands/features that will simplify our development process but it was also useful discussing our k8s-router with him.  I definitely think we should submit a talk next year, or a few.
