### ISSUE TITLE
Figure out customer-facing logging

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#118]
@madhurranjan has implemented container/host logging for Kubernetes as a whole.  The problem is we need customers to be able to access their logs, and only their logs.  We need to figure out if Mamu's logging solution is something we can securely provide to customers or if we need to extend `enrober` to provide Shipyard customers with their deployment logs.

**Comment by noahdietz** [comment]
This is addressed by the [`logpull` service](https://github.com/30x/logpull).

`GET /logs/environments/{org}-{env}/deployments/{dep}`
- validates Apigee org admin privileges 
- pulls all available logs for all containers belonging to the deployment in that namespace
- has a `tail` query string param
- doesn't differentiate logs for each container, streams all in indexed order

A separate service was made to keep `enrober` from growing and Elasticsearch queries are made instead of k8s `log` API calls in order to reduce load on the apiserver

**Comment by jbowen93** [comment]
I believe this is solved by issue #52 which will be merged with PR #53.

**Comment by jbowen93** [comment]
Closing this because PR #53 is merged.
