### ISSUE TITLE
Enrober and Build Service are not secured

### ISSUE THREAD

**Issue by mpnally** [30x/project-management#124]
Currently there is no key protecting either the "Shipyard" namespace in which the build service runs or the "Apigee" namespace in which Enrober runs. This means that anyone on the cluster can send messages to these services without protection. This has to be changed before beta. The simplest fix seems to me to be the following:
- Create a "shipyard-infrastructure" namespace. It has no keys.  It has no hostnames either. The public and private routers go in there.
- Create a "shipyard-management" namespace. SSO, Enrober and the build service go in there. It has a key. It has the hostname  It has no hostnames either. It has no hostnames either.

It is possible to separate Enrober from the build service in different namespaces, but this makes key management a bit more complex. Either both namespaces have to have the same key, or the Edge proxy has to have both keys and juggle which key to use according to the path, which is a mess (Enrober would need the key for the build service namespace too).

**Comment by whitlockjc** [comment]
Locking down external traffic would be as simple as adding the public API Key secret to the `apigee` namespace and updating the Edge proxy to set the header appropriately.  We do not want to set a private API Key secret because the SSO Proxy is unable to juggle changing the API Keys after it authenticates the user and proxies to the private proxy.  This should be enough because we should be using network policies to lock down traffic from other namespaces reaching the non-router pods.  Thoughts?

**Comment by mpnally** [comment]
I think Enrober has to access the Build Service. Node applications in other
namespaces must not be able to. How can that work without a private key?

Martin

**Comment by mpnally** [comment]
P.S. I didn't understand what the problem is with SSO proxy and private
keys.

Martin

**Comment by jbowen93** [comment]
Both services are now secured. However at this time we are using the same public and private routing keys for both the `apigee` and `shipyard` namespaces. Still need to resolve the issue of the SSO proxy being unable to juggle keys for public/private routing.

**Comment by mpnally** [comment]
It is not clear to me that "the SSO proxy being unable to juggle keys" is a problem. I can make an argument that it is a feature.
