### ISSUE TITLE
Run Auth app aka Ganyo proxy in k8s

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#55]
This does the OAuth dance with Apigee SSO and  proxies build API (Todd) and deploy API (Josh).

Example: Auth app will be configured to listen on on / and accept host header edgex.apigee.com . An Apigee org admin would make a POST call to edgex.apgiee.com/build, the app would make sure that it has right token and send request to /build on private port.

**Comment by whitlockjc** [comment]
The plan for this task is to update the SSO Proxy source base to document and support building a Docker image from the project.  From a Kubernetes perspective, we have a number of ways to configure the SSO Proxy and this is what I would suggest doing in Kubernetes:

**Environment Setup**
- Create an `sso-proxy` secret in Kubernetes
- Create a `public-key` data field in the secret created above _(This will be used to set the `SSO_PUBLIC_KEY` environment variable for the SSO Proxy container)_
- Create an `oauth-client-id` data field in the secret created above _(This will be used to set the `SSO_CLIENT_ID` environment variable for the SSO Proxy container)_
- Create an `oauth-client-secret` data field in the secret created above _(This will be used to set the `SSO_CLIENT_SECRET` environment variable for the SSO Proxy container)_

**Note:** The 2nd and 3rd steps could be done without using secrets since their value is not itself a secret but for centralization of configuration, it seemed like a decent idea.

**SSO Proxy Deployment**

Create the proper Kubernetes deployment configuration that wires in the environmental things where necessary.

**Status**

The Docker part of this task has been completed, minus the need to create a location for the SSO Proxy on DockerHub and push the image.  Where I am currently blocked is the Kubernetes part requires us to create the Edge proxy first and then based on that proxy, we will have the necessary pieces of information, like the OAuth client id/secret, to create the necessary Kubernetes environment.

Assigning to @prabhatjha.
