### ISSUE TITLE
Create permission service sdk

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#79]
Service that build and deploy API would use to see if user is authorized to build and deploy respectively.

**Comment by prabhatjha** [comment]
For alpha, it will be a stub.

**Comment by tnine** [comment]
Building this as an interface.  For the first pass the SDK will be completely client side, and validate the token and the user only.  Eventually this SDK will call a remote service.

**Comment by mpnally** [comment]
When you say "validate the user", that means "validate that the user is an org-admin in the appropriate org", right?

Martin

**Comment by mpnally** [comment]
I don't read Go very well, but I think this API requires me to create a new instance of a `JWTToken` struct, and then use the `IsOrgAdmin` method of the struct. Is that right? If I am understanding this correctly, I think this could be improved. Having `IsOrgAdmin` as a method of a `JWTToken` seems odd to me. Also, the API seems wider than necessary. Why not have simply `func IsOrgAdmin(orgName string, token string) (bool, error)`? That would avoid exposing clients to your `JWTtoken` class, which can remain internal

**Comment by mpnally** [comment]
There is another reason why I'm not very comfortable with this SDK design. The SDK is supposed to be '0.1' version of the SDK for the permissions service. In the permission service, neither org nor orgAdmin are concepts, so the method `IsOrgAdmin` does not fit the model. Page 3 of this document describes what we are trying to do: `https://docs.google.com/a/apigee.com/document/d/1Mpc26e4sNI_KcZbNIQnS9rxDA3AFfGxrLp5DasfkFyQ/edit?usp=sharing`. The underlying API resources look like this `/allowed-actions{?resource,user}`. Both resource and user are URLs. The resource we are testing happens to be an Org for the alpha, but this will change. The user can be derived from the incoming token. An SDK method signature that makes sense to me would be `func AllowedActions(resourceURL string, token string) (string, error)`. (Unless there is a tradition in Golang of modeling URLs explicitly rather than using strings). For the alpha, the implementation will decide the allowed actions by figuring out if the user is an org admin, but we don't want this to leak through the SDK interface because this will change when we get the real permissions service working.

**Comment by tnine** [comment]
I'm all for revising this.  This is a very rough implementation to have caching functionality  due to the poor performance of the permissions GET.  I'm all for changing it, but I don't want to do so before our Alpha release.
