### ISSUE TITLE
Update internal design document to reflect changes

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#98]
The k8s-pods-ingress has deviated a little bit from the original design document @mpnally wrote.  We should get that updated with any changes _(not just the router)_ that have deviated from the original document.

**Comment by mpnally** [comment]
Affected documents include: https://docs.google.com/a/apigee.com/document/d/1LWUzdVAa4iv7hBXDgfi809lHYbwdm7Sr46LNCcvtKhI/edit?usp=sharing
https://docs.google.com/a/apigee.com/document/d/1KxUv2OAtGQkO8qE_TlWdjIi2JuekCLvZKTMS8ldBtAs/edit?usp=sharing
https://docs.google.com/a/apigee.com/document/d/1k0BK79PgOwYL1-KYuxap-8h4Fr9PcbceUQfcrjPlq50/edit?usp=sharing

**Comment by mpnally** [comment]
Upon closer inspection, only https://docs.google.com/a/apigee.com/document/d/1LWUzdVAa4iv7hBXDgfi809lHYbwdm7Sr46LNCcvtKhI/edit?usp=sharing was affected. Note that the documentation says that publicHost and privateHosts are annotations on the replicationController/replicaSet, rather that on the Pod Template spec as currently implemented. Since we intend to bring the implementation in line with the spec, I have left the spec as it is.
